export default function TermsPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        background: "#050505",
        color: "#fff",
        padding: "40px 20px",
      }}
    >
      <div style={{ maxWidth: "850px", margin: "0 auto" }}>
        <h1>Terms & Conditions</h1>

        <p>Last Updated: 1 June 2026</p>

        <h2>1. Acceptance of Terms</h2>

        <p>
          By accessing or using SlickyMicky.com, you agree to these Terms
          and Conditions. If you do not agree, please stop using this website.
        </p>

        <h2>2. Entertainment Purposes Only</h2>

        <p>
          Slicky Micky is an AI-powered entertainment experience. All messages,
          responses, predictions, statements, and generated content are created
          for entertainment, humour, curiosity, and fictional purposes only.
        </p>

        <p>
          Content generated by Slicky Micky should not be considered factual,
          personal knowledge, professional advice, or a prediction of future
          events.
        </p>

        <h2>3. Artificial Intelligence Disclaimer</h2>

        <p>
          Slicky Micky uses artificial intelligence technology. AI-generated
          responses may be fictional, inaccurate, incomplete, unexpected, or
          incorrect.
        </p>

        <p>
          Any resemblance to real people, events, emotions, thoughts,
          relationships, or circumstances is purely coincidental.
        </p>

        <h2>4. User Responsibility</h2>

        <p>
          You understand that all use of this website is at your own discretion.
          You are responsible for how you interpret or use any generated
          content.
        </p>

        <h2>5. Payments</h2>

        <p>
          Slicky Micky may offer paid digital services including AI-generated
          messages, additional access, subscriptions, or other digital products.
        </p>

        <p>
          Payments are processed securely through third-party payment providers.
          We do not store your full payment card information.
        </p>

        <h2>6. Refund Policy</h2>

        <p>
          All purchases are final.
        </p>

        <p>
          Due to the immediate delivery of digital content and AI-generated
          responses, refunds, exchanges, or credits will not be provided for
          change of mind, dissatisfaction with generated content, or unused
          services.
        </p>

        <p>
          This does not exclude any rights that cannot legally be excluded under
          applicable consumer protection laws.
        </p>

        <h2>7. Subscriptions</h2>

        <p>
          If subscription services are available, subscriptions automatically
          renew until cancelled. Users are responsible for managing and
          cancelling subscriptions before renewal dates.
        </p>

        <h2>8. Intellectual Property</h2>

        <p>
          Slicky Micky, including the name, branding, character, website design,
          text, graphics, videos, and creative content remain our intellectual
          property.
        </p>

        <p>
          Content may not be copied, reproduced, sold, or redistributed without
          permission.
        </p>

        <h2>9. Website Availability</h2>

        <p>
          We do not guarantee uninterrupted access to SlickyMicky.com. The
          website may be changed, suspended, updated, or removed at any time.
        </p>

        <h2>10. Limitation of Liability</h2>

        <p>
          To the maximum extent permitted by law, SlickyMicky.com and its owners
          are not responsible for losses, damages, emotional distress, decisions
          made, or consequences resulting from use of the website or generated
          content.
        </p>

        <h2>11. Third Party Services</h2>

        <p>
          Slicky Micky may use third-party services including payment providers,
          hosting services, analytics providers, and AI technology providers.
        </p>

        <h2>12. Governing Law</h2>

        <p>
          These Terms are governed by the laws of Victoria, Australia. Mandatory
          consumer rights in other jurisdictions remain unaffected.
        </p>

        <h2>13. Contact</h2>

        <p>
          Questions regarding these Terms can be sent to:
          support@slickymicky.com
        </p>
      </div>
    </main>
  );
}